### ISSUE TITLE
Add redmine

### ISSUE THREAD

**Issue by Heinerion** [Heinerion/docker-compose-sonarqube#1]
Redmine already offers a docker-compose script:

```yaml
version: '2'

services:

  redmine:
    image: redmine
    ports:
      - 8080:3000
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: example
    depends_on:
      - db
    restart: always

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: redmine
    restart: always
```

Adjustments: Use Postgre as with docker (but another instance)

see https://hub.docker.com/_/redmine/
